startToUpload = "`%s` start uploading, size:`%s`"
completeUpload = "%s upload completed, time consuming %d s,average upload speed %s/s"
configCreateSuccess = "The registration is successful. A new login file has been created in the running directory:%s"
telegramSendError = "Telegram Send Error:%s"
failToLoadFiles = "Failed to Load Files from source :%v"
startToUpload1 = "start uploading to onedrive"
oneDriveBigFile = "File: `%s` Start upload to OneDrive\nAccounts:`%s`\nFile over 4MB, go to large file channel"
oneDriveSmallFile = "File: `%s` Start upload to OneDrive\nAccounts:`%s`\nFile less than 4MB, go to small file channel, uploading in progress"
failToStore = "Failed to Restore :%v"
failToLink = "OneDrive account `%s` \n There was a connection problem when uploading `%s` Retrying. This is the %d times retrying"
oneDriveUploadTip1 = "OneDrive account `%s` \nUploading `%s`\nSize:`%s` Complete: `%s` Progress: *『%d/%d』*  \nSpeed:`%s/s` \nTime: `%d s`"
oneDriveUploadTip2 = "OneDrive account `%s` \nUploading `%s`\nSize:`%s` Complete: `%s` Progress: *『%d/%d』*  \nSpeed:`----` \nTime: `%d s`"